language: java
os: linux
dist: bionic
services:
  - docker
branches:
  only:
    - master
before_cache:
  - rm -rf $HOME/.gradle/caches/9.*/
  - rm -rf $HOME/.gradle/caches/8.*/
  - rm -rf $HOME/.gradle/caches/7.*/
  - rm -rf $HOME/.gradle/caches/6.*/
  - rm -rf $HOME/.gradle/caches/5.*/
  - rm -rf $HOME/.gradle/caches/4.*/
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - find ~/.gradle/caches/ -name "*.lock" -type f -delete
cache:
  bundler: false
  cargo: false
  directories:
    - $HOME/.m2
    - $HOME/.npm/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
git:
  depth: 1
env:
  global:
    - JAVA_OPTS="-Xms512m -Xmx6048m -Xss64m -XX:ReservedCodeCacheSize=512m -Xverify:none -server -XX:+UseG1GC"
    - GRADLE_OPTS="-Xms512m -Xmx6048m -Xss64m -XX:ReservedCodeCacheSize=512m -Xverify:none -server -XX:+UseG1GC"
    - SPRING_MAIN_BANNER-MODE="off"
    - TERM=xterm
jdk:
  - openjdk11
install:
  - echo "Travis CI is disabled"
script:
  - echo "Travis CI is disabled"

