# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt VAR_NAME=[OAUTH-TOKEN] -r apereo/cas --add env.global

language: java
sudo: required
branches:
  only:
  - master
jdk:
- oraclejdk8
# - oraclejdk9
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/    
git:
  depth: 1
notifications:
  slack: apereo:tUFPsW9tmnzVSADu1LqqSUV8
matrix:
  fast_finish: true
env:
  global:
  - secure: "ScUSTo0if5m7ddnwUA7EaYucc6yzEUrKLk0DzCvkMfjn2h5taUFSKHx+S0hd2EzJofv+Em4eI5qncSK5LTxgD7HhHR1e3iZp+SqJenhhOnbuciZfg4QA+tUGw3XUdmREac5cz2l0qhi1q4vsnnZARj2d4vvf2HWuNtEOBu/ZAKI="
  - secure: "iWPPLKSS3zBs2adqLPkMiHfCj2hSLyD5BoV3oodhR7Ne83Kpn1khRcEWFoHF3Ed11eSU+glNdPSzUpc8TzwTZGx5B3RU2Qp36hZFyjuzNWJARmoVPYMiEg3FFBQrUR75w+Tbtn6zPkiAk6nl0K5ewmY0/xixVdnTLXL5HjpE2rc="
  - secure: "f3mDIZ8m6NYJXI8KvWD/sZRSeCCyIyfgPRy3Q6o9u9WyHZuYaJf95Ia0eJQ3gxUDS1TKL31Vk08dhFKrfIcKgifFPa2uQ2uyJkvGxlarMTQ+tpqsZYp4zAJgKc9r4xdZasvF2k4xqr+pl9AFjlpXB4jDD59XPXt3DcRABOYA9sM="
  matrix:
  - PUBLISH_SNAPSHOTS=false
  - PUBLISH_SNAPSHOTS=true
before_install:
- export JAVA_OPTS="-Xmx2048m"
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
install:
- chmod -R 777 ./travis/install.sh
- ./travis/install.sh
script:
- chmod -R 777 ./travis/install.sh
- ./travis/script.sh
after_success:
- chmod -R 777 ./travis/push-javadoc-to-gh-pages.sh
- ./travis/push-javadoc-to-gh-pages.sh
