# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt VAR_NAME=[OAUTH-TOKEN] -r apereo/cas --add env.global
#

language: java
sudo: required
branches:
  only:
  - 5.0.x
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.gradle/caches'
env:
  global:
  - secure: "JlFTItSTHxmevCoX1fXWkXtQOqP8ERT5ndeYMc378acqZIWEpmoSQelP8unRjtU6sU/4dxdUWpEFLrbcNQsFuPsgzMLGSwuEcjbuSBGMgdAHXSl6+FfBWrCcde2WIfk+eYMm7mrhcySWMvtWss1kDOu+s8+HtRvnRCAsfz+77hs="
  - secure: "iWPPLKSS3zBs2adqLPkMiHfCj2hSLyD5BoV3oodhR7Ne83Kpn1khRcEWFoHF3Ed11eSU+glNdPSzUpc8TzwTZGx5B3RU2Qp36hZFyjuzNWJARmoVPYMiEg3FFBQrUR75w+Tbtn6zPkiAk6nl0K5ewmY0/xixVdnTLXL5HjpE2rc="
  - secure: "f3mDIZ8m6NYJXI8KvWD/sZRSeCCyIyfgPRy3Q6o9u9WyHZuYaJf95Ia0eJQ3gxUDS1TKL31Vk08dhFKrfIcKgifFPa2uQ2uyJkvGxlarMTQ+tpqsZYp4zAJgKc9r4xdZasvF2k4xqr+pl9AFjlpXB4jDD59XPXt3DcRABOYA9sM="
before_script:
 - export JAVA_OPTS="-Xmx2048m"
before_install:
- ls ./etc
- sudo unzip -j -o ./etc/jce8.zip *.jar -d `jdk_switcher home oraclejdk8`/jre/lib/security
- sudo ls `jdk_switcher home oraclejdk8`/jre/lib/security
- sudo cp ./etc/java.security `jdk_switcher home oraclejdk8`/jre/lib/security
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
- chmod -R 777 ./gradlew
install:
- ./gradlew clean bootRepackage install --parallel -x test --stacktrace
script:
- travis_wait ./gradlew test --stacktrace --parallel
after_success:
- chmod -R 777 ./travis/push-javadoc-to-gh-pages.sh
- ./travis/push-javadoc-to-gh-pages.sh
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
