# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt VAR_NAME=[OAUTH-TOKEN] -r apereo/cas --add env.global
# Encrypted settings include SONATYPE_USER, SONATYPE_PWD, GH_TOKEN, COVERITY_SCAN_TOKEN

language: java
sudo: true
dist: trusty
services:
  - docker
branches:
  only:
  - master
jdk:
- oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/    
git:
  depth: 1
notifications:
  slack: apereo:tUFPsW9tmnzVSADu1LqqSUV8
matrix:
  fast_finish: true
env:
  global:
  - JAVA_OPTS="-Xms512m -Xmx2048m -Xss128m -XX:ReservedCodeCacheSize=512m"
  - SPRING_MAIN_BANNER-MODE="off"
  - secure: "ScUSTo0if5m7ddnwUA7EaYucc6yzEUrKLk0DzCvkMfjn2h5taUFSKHx+S0hd2EzJofv+Em4eI5qncSK5LTxgD7HhHR1e3iZp+SqJenhhOnbuciZfg4QA+tUGw3XUdmREac5cz2l0qhi1q4vsnnZARj2d4vvf2HWuNtEOBu/ZAKI="
  - secure: "iWPPLKSS3zBs2adqLPkMiHfCj2hSLyD5BoV3oodhR7Ne83Kpn1khRcEWFoHF3Ed11eSU+glNdPSzUpc8TzwTZGx5B3RU2Qp36hZFyjuzNWJARmoVPYMiEg3FFBQrUR75w+Tbtn6zPkiAk6nl0K5ewmY0/xixVdnTLXL5HjpE2rc="
  - secure: "f3mDIZ8m6NYJXI8KvWD/sZRSeCCyIyfgPRy3Q6o9u9WyHZuYaJf95Ia0eJQ3gxUDS1TKL31Vk08dhFKrfIcKgifFPa2uQ2uyJkvGxlarMTQ+tpqsZYp4zAJgKc9r4xdZasvF2k4xqr+pl9AFjlpXB4jDD59XPXt3DcRABOYA9sM="
before_install:
- chmod -R 777 ./ci/run-ldap-server.sh
- ./ci/run-ldap-server.sh
- chmod -R 777 ./ci/run-mail-server.sh
- ./ci/run-mail-server.sh
- chmod -R 777 ./ci/run-influxdb-server.sh
- ./ci/run-influxdb-server.sh
- chmod -R 777 ./ci/run-dynamodb-server.sh
- ./ci/run-dynamodb-server.sh
- chmod -R 777 ./ci/run-couchbase-server.sh
- ./ci/run-couchbase-server.sh
- chmod -R 777 ./ci/run-cassandra-server.sh
- ./ci/run-cassandra-server.sh
- chmod -R 777 ./ci/init-travis-build.sh
- ./ci/init-travis-build.sh
- chmod -R 777 ./ci/push-docs-ghpages.sh
- ./ci/push-docs-ghpages.sh
install:
- chmod -R 777 ./ci/install.sh
- ./ci/install.sh
script:
- chmod -R 777 ./ci/script.sh
- ./ci/script.sh
after_script:
- chmod -R 777 ./ci/stop.sh
- ./ci/stop.sh
stages:
  - build
  - test
  - doc
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: build
      env: MATRIX_JOB_TYPE=BUILD
    - stage: test
      env:
        - MATRIX_JOB_TYPE=TEST
        - MATRIX_JOB_TYPE=STYLE
    - stage: doc
      env:
        - MATRIX_JOB_TYPE=JAVADOC
        - MATRIX_JOB_TYPE=DEPUPDATE
        - MATRIX_JOB_TYPE=CFGMETADATA
        - MATRIX_JOB_TYPE=DEPANALYZE
    - stage: deploy
      env: MATRIX_JOB_TYPE=SNAPSHOT
