# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt VAR_NAME=[OAUTH-TOKEN] -r apereo/cas --add env.global
#

language: java
sudo: required
branches:
  only:
  - master
jdk:
- oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/    
git:
  depth: 1
notifications:
  slack: apereo:tUFPsW9tmnzVSADu1LqqSUV8
env:
  global:
  - secure: "ScUSTo0if5m7ddnwUA7EaYucc6yzEUrKLk0DzCvkMfjn2h5taUFSKHx+S0hd2EzJofv+Em4eI5qncSK5LTxgD7HhHR1e3iZp+SqJenhhOnbuciZfg4QA+tUGw3XUdmREac5cz2l0qhi1q4vsnnZARj2d4vvf2HWuNtEOBu/ZAKI="
  - secure: "iWPPLKSS3zBs2adqLPkMiHfCj2hSLyD5BoV3oodhR7Ne83Kpn1khRcEWFoHF3Ed11eSU+glNdPSzUpc8TzwTZGx5B3RU2Qp36hZFyjuzNWJARmoVPYMiEg3FFBQrUR75w+Tbtn6zPkiAk6nl0K5ewmY0/xixVdnTLXL5HjpE2rc="
  - secure: "f3mDIZ8m6NYJXI8KvWD/sZRSeCCyIyfgPRy3Q6o9u9WyHZuYaJf95Ia0eJQ3gxUDS1TKL31Vk08dhFKrfIcKgifFPa2uQ2uyJkvGxlarMTQ+tpqsZYp4zAJgKc9r4xdZasvF2k4xqr+pl9AFjlpXB4jDD59XPXt3DcRABOYA9sM="
before_script:
 - export JAVA_OPTS="-Xmx2048m"
before_install:
- sudo mkdir -p /etc/cas/config /etc/cas/saml /etc/cas/services
- sudo unzip -j -o ./etc/jce8.zip *.jar -d `jdk_switcher home oraclejdk8`/jre/lib/security
- sudo ls `jdk_switcher home oraclejdk8`/jre/lib/security
- sudo cp ./etc/java.security `jdk_switcher home oraclejdk8`/jre/lib/security
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
- chmod -R 777 ./gradlew
- sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get update
- sudo apt-get install -y nodejs
- sudo ./gradlew npmInstall gulpSetup --stacktrace -q
install:
- sudo ./gradlew clean checkstyleMain bootRepackage install --parallel -x test --stacktrace
script:
- travis_wait sudo ./gradlew checkstyleTest test --stacktrace --parallel
after_success:
- chmod -R 777 ./travis/push-javadoc-to-gh-pages.sh
- ./travis/push-javadoc-to-gh-pages.sh
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- travis_wait ./travis/deploy-to-sonatype.sh
