casbot:
  github:
    repository:
      organization: apereo
      name: cas
      collaborators:
        - bclozel
        - mbhave
        - philwebb
        - snicoll
        - wilkinsona
  triage:
    label: "status: waiting-for-triage"
  feedback:
    required_label: "status: waiting-for-feedback"
    provided_label: "status: feedback-provided"
    reminder_label: "status: feedback-reminder"
    reminder_comment: >
      If you would like us to look at this issue, please provide the requested
      information. If the information is not provided within the next 7 days this issue
      will be closed.
    close_comment: >
      Closing due to lack of requested feedback. If you would like us to look at this
      issue, please provide the requested information and we will re-open the issue.
