logging:
  level:
    root: warn
    org:
      apereo:
        cas: info
casbot:
  github:
    repository:
      organization: apereo
      name: cas
      url: https://github.com/apereo/cas
      committers: mmoayyed,leleuj,hdeadman

spring:
  security:
    user:
      name: apereocasbot
      password: ${CASBOT_GITHUB_CREDENTIALS_TOKEN}
