name: Dependencies

env:
  JAVA_OPTS: "-Xms512m -Xmx8048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  TERM: xterm-256color
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
  GH_PACKAGE_REGISTRY_USER: ${{ secrets.GH_PACKAGE_REGISTRY_USER }}
  GH_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  JDK_CURRENT: 21
  JDK_DISTRIBUTION: "corretto"

##########################################################################

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: write
  pull-requests: write
  
##########################################################################

jobs:
  initialize:
    name: Initialize Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.JDK_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Initialize
        run: ls ./ci && find ./ci -type f -name "*.sh" -exec chmod +x "{}" \; && ./ci/init-build.sh

##########################################################################

  report-dependency-updates:
    runs-on: ubuntu-latest
    needs: [initialize]
    name: Report Dependency Updates
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.JDK_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Initialize
        run: find ./ci -type f -name "*.sh" -exec chmod +x "{}" \; && ./ci/init-build.sh
      - name: Report Dependency Updates
        run: |
          ./gradlew dependencyUpdates --build-cache --configure-on-demand --no-daemon --parallel -x test -x javadoc \
            -x check --no-configuration-cache -Drevision=release -DskipAot=true -DskipNestedConfigMetadataGen=true \
            -DgradleReleaseChannel=current --max-workers=8 -DreportfileName=dependencies \
            -DoutputFormatter=json,plain -DoutputDir=./build/reports/dependency-updates
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: dependency-updates
          path: ./build/reports/dependency-updates/dependencies.json
          if-no-files-found: ignore
          retention-days: 2
  ##########################################################################

  submit-dependency-graph:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest
    needs: [initialize]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.JDK_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Initialize
        run: find ./ci -type f -name "*.sh" -exec chmod +x "{}" \; && ./ci/init-build.sh
      - name: Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4

  ##########################################################################

  renovate:
    runs-on: ubuntu-latest
    needs: [initialize]
    timeout-minutes: 60
    name: Run Renovate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: info
          RENOVATE_REPOSITORIES: ${{ github.repository }}
