name: Puppeteer

##########################################################################

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  GRADLE_BUILDCACHE_USER: ${{ secrets.GRADLE_BUILDCACHE_USER }}
  GRADLE_BUILDCACHE_PSW: ${{ secrets.GRADLE_BUILDCACHE_PSW }}
  TERM: xterm-256color
  JDK_CURRENT: 11.0.10

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ labeled ]
    branches: [ master ]

##########################################################################

jobs:
  cancel-previous-runs:
    if: ${{ (github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'CI')) && !contains(github.event.head_commit.message, 'trigger dependency update') && !contains(github.event.head_commit.message, 'documentation update') }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

  initialize:
    needs: [cancel-previous-runs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_CURRENT }}
      - name: Initialize
        run: ls ./ci && chmod -R 777 ./ci/*.sh && ./ci/init-build.sh

##########################################################################
  puppeteer-tests:
    runs-on: ubuntu-latest
    needs: [initialize]
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - login-success
          - block-missing-service
          - default-service
          - requiredattrs-service
          - invalid-pswd-reset
          - locale-param
          - generate-service-ticket
          - webauthn-primary-authn
          - authn-throttle
          - qrauthn-login
          - gauth-register
          - gauth-login
          - adaptive-login-blocked
          - duo-websdk-login
          - duo-universal-login
          - mfa-provider-selection
          - x509-optional-login
          - actuator-form-login
          - unauthz-service
          - account-locked-login
          - account-disabled-login
          - account-expired-login
          - account-change-pswd
          - account-invalidloc-login
          - account-invalidtime-login
          - ticket-validation-casv1
          - ticket-validation-casv2
          - ticket-validation-casv3
          - ticket-validation-casv3-json
          - ticket-validation-saml1
          - mfa-inwebo-browser
          - mfa-inwebo-push
          - aup-login
          - authy-mfa-login
          - logout-confirm
          - gua-login
          - surrogate-login-selection
          - simple-mfa-login
          - interrupt-login
          - oidc-authzcode-login
          - oidc-debugger-code-login
          - oidc-debugger-token-login
          - oidc-debugger-idtoken-login
          - oidc-debugger-idtoken-token-login
          - pac4j-delegated-login
          - pac4j-delegated-saml-login
          - renew-existing-sso
          - passwordless-requirepswd-login
          - passwordless-delegated-login
          - passwordless-mfa-login
          - passwordless-login
          - mfa-provider-unavailable
          - source-selection-login
          - custom-fields-login
          - forgot-username
          - forgot-username-recaptcha
          - forgot-password
          - forgot-password-recaptcha
          - attribute-consent
          - u2f-register
          - u2f-login
          - recaptcha-login-v2
          - recaptcha-login-v3
          - hcaptcha-login
          - webauthn-register
          - webauthn-login
          - saml2-idp-login
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_CURRENT }}
      - name: Initialize
        run: chmod -R 777 ./ci/*.sh
      - name: Run Tests
        run: ./ci/tests/puppeteer/run.sh $PWD/ci/tests/puppeteer/scenarios/${{matrix.scenario}}
##########################################################################
