name: Release

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server"
  TERM: xterm-256color
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  REPOSITORY_USER: ${{ secrets.REPOSITORY_USER }}
  REPOSITORY_PWD: ${{ secrets.REPOSITORY_PWD }}
  JDK_CURRENT: 21
  JDK_DISTRIBUTION: "corretto"

##########################################################################

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_snapshot: ${{ steps.check.outputs.is_snapshot }}
    steps:
      - uses: actions/checkout@v5
      - name: Determine version
        id: check
        run: |
          casVersion=(`cat ./gradle.properties | grep "version" | cut -d= -f2`)
          echo "Detected version: $casVersion"

          # decide if itâ€™s a SNAPSHOT
          if [[ "$casVersion" == *-SNAPSHOT ]]; then
            echo "is_snapshot=true"
          else
            echo "is_snapshot=false"
          fi \
          >> $GITHUB_OUTPUT
  release-to-central:
    runs-on: ubuntu-latest
    if: needs.check.outputs.is_snapshot == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.JDK_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Initialize
        run: find ./ci -type f -name "*.sh" -exec chmod +x "{}" \; && ./ci/init-build.sh
      - name: Configure PGP
        run: echo "$PGP_PRIVATE_KEY" | gpg --batch --import
      - name: Release
        run: chmod +x ./ci/release.sh && ./ci/release.sh
